namespace java com.sankuai.octo.log.statistic.model

include 'QpsLog.idl'

enum QpsRetrieveCode {
    SUCCESS,
    NOT_EXIST,
    TIME_OUT_OF_RANGE
}

struct QpsResult {
    1:QpsRetrieveCode code;
    /*key的类型为consumerAppKey*/
    2:map<string,list<QpsLog.QpsLog>> qpsLogMap;
}