CFLAGS = -g -Wno-deprecated -DHAVE_NETINET_IN_H

INCLUDE =-I./ \
		-I../.. \
		-I../../thrift \
		-I../../thrift/transport \
        -I../../thrift/async \
        -I../../thrift/concurrency \
        -I../../thrift/processor \
        -I../../thrift/protocol \
        -I../../thrift/qt \
        -I../../thrift/server \
		-I../../../util \
		-I../../../comm \
		-I../../../mtconfig \
		-I../config \
		-I/usr/local/java/include \
		-I/usr/local/java/include/linux \

LIB = -L./  -levent \
	-lpthread \
	-lm \

VPATH = ../../../util \
		../../../comm/ \
		../../../mtconfig \
		../config \
		../../thrift \
        ../../thrift/async \
        ../../thrift/concurrency \
        ../../thrift/processor \
        ../../thrift/protocol \
        ../../thrift/qt \
        ../../thrift/server \
        ../../thrift/transport \


OUTPUT  = sg_agent_conf

OBJS    = sg_agent_config_client.o \
		sg_agent_config_client.o \
		sg_agent_config_processor.o \
		SGAgent.o \
		MtConfig_types.o \
		sgagent_types.o \
		php_sg_agent_config_client.o \
		Thrift.o \
		TBufferTransports.o \
		TApplicationException.o \
		TSocket.o \
		MtConfig_types.o \
		sgagent_types.o \
		main.o \


all:$(OUTPUT)

.SUFFIXES: .o .cpp
.cpp.o:
	$(CXX) $(CFLAGS) $(INCLUDE) -c $^

.o:
	$(CXX) $(CFLAGS) $(INCLUDE) -o $@ $^

$(OUTPUT): $(OBJS)
	$(CXX) $(CFLAGS) -o $@ $^ ${LIB}

clean:
	rm -f *.o *.~ *.bak
	rm -f $(OUTPUT)

dep:
	mkdep $(INCLUDE) $(SOURCES) > .depend

ifneq ($(wildcard .depend),)
include .depend
endif
