version: v1
common:
  tools:
    oracle-jdk: 7
  env:
    CURRENT_ENV: offline
    APP_KEY: com.sankuai.inf.mnsc
    WORK_PATH: /opt/meituan/mobile/mns-cache
    MODULE: mns-cache
    PACKAGE_PATH: mns-cache
    TEST_URL: http://127.0.0.1:8911/api/monitor/alive
build: 
  tools:
    maven: 3.3.3
  run:
    workDir: mns/mns-cache/
    cmd: 
      - sh deploy/compile.sh
  target: 
    distDir: mns/mns-cache/target/
    files: 
      - ./*.war
      - ../deploy
autodeploy:
    targetDir: /opt/meituan/mobile/mns-cache/
    env:
    run: sh deploy/run.sh
    check: sh /opt/meituan/mobile/mns-cache/deploy/check.sh
    checkRetry: 1 # 缺省值为1，可加大增加check命令执行次数，拉长检查时间
    checkInterval: 1s # 缺省值为1s，建议此数值不宜过大。
    daemonToolsStopTimeout: 30s # 如果通过octo控制流量，需要将此项设置大点为30s。否则，无需设置该项，默认10s。
deploy: 
  targetDir: /opt/meituan/mobile/mns-cache/
  tools:
  run:
    workDir: /opt/meituan/mobile/mns-cache/
    cmd: 
      - sh deploy/run.sh
