version: v1
common:
  os: centos7
  tools:
    oracle-jdk: 7
  env:
    CURRENT_ENV: online
build:
  tools:
    maven: 3.3.3
  run:
    workDir: data-center/data-statistic/
    cmd:
      - sh deploy/compile.sh
  target:
    distDir: data-center/data-statistic/target/
    files:
      - ./*.war
      - ../deploy
deploy:
  targetDir: /opt/meituan/apps/data-statistic/
  tools:
  run:
    workDir: /opt/meituan/apps/data-statistic/
    cmd:
      - sh deploy/post_deploy_opsplus.sh