/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef castle_service_TYPES_H
#define castle_service_TYPES_H

#include <Thrift.h>
#include <TApplicationException.h>
#include <protocol/TProtocol.h>
#include <transport/TTransport.h>

#include "castle_data_types.h"




typedef class  ::HeartBeatRequest HeartBeatRequest;

typedef class  ::HeartBeatResponse HeartBeatResponse;

typedef class  ::ClientInfoRequest ClientInfoRequest;

typedef class  ::ClientInfoResponse ClientInfoResponse;

typedef class  ::TopicConfig TopicConfig;

typedef class  ::TopicMonitorInfo TopicMonitorInfo;

typedef class  ::ConsumerGroupConfig ConsumerGroupConfig;

typedef class  ::ConsumerGroupMonitorInfo ConsumerGroupMonitorInfo;

typedef class  ::TopicInfo TopicInfo;

typedef class  ::ConsumerGroupInfo ConsumerGroupInfo;

typedef class  ::TopicConfigRequest TopicConfigRequest;

typedef class  ::TopicActionResponse TopicActionResponse;

typedef class  ::TopicConfigResponse TopicConfigResponse;

typedef class  ::TopicInfoResponse TopicInfoResponse;

typedef class  ::ConsumerGroupConfigRequest ConsumerGroupConfigRequest;

typedef class  ::TopicInfoListResponse TopicInfoListResponse;

typedef class  ::ConsumerGroupListResponse ConsumerGroupListResponse;

typedef class  ::ClusterNameRequest ClusterNameRequest;

typedef class  ::ConsumerGroupInfoResponse ConsumerGroupInfoResponse;



#endif
