version: v1
common:
  tools:
    oracle-jdk: 7
  env:
    CURRENT_ENV: offline
    APP_KEY: com.sankuai.inf.sgnotify
    WORK_PATH: /opt/meituan/apps/sgnotify
    MODULE: sgnotify
    PACKAGE_PATH: sgnotify
build:
  tools:
    maven: 3.3.3
  run:
    workDir: mns/sgnotify/
    cmd: 
      - sh deploy/compile.sh
  target: 
    distDir: mns/sgnotify/target/
    files: 
      - ./*.war
      - ../deploy
autodeploy:
    targetDir: /opt/meituan/apps/sgnotify/
    env:
    run: sh deploy/run.sh
    check: sh /opt/meituan/apps/sgnotify/deploy/check.sh
    checkRetry: 1 # 缺省值为1，可加大增加check命令执行次数，拉长检查时间
    checkInterval: 1s # 缺省值为1s，建议此数值不宜过大。
    daemonToolsStopTimeout: 30s # 如果通过octo控制流量，需要将此项设置大点为30s。否则，无需设置该项，默认10s。
deploy: 
  targetDir: /opt/meituan/apps/sgnotify/
  tools:
  run:
    workDir: /opt/meituan/apps/sgnotify/
    cmd: 
      - sh deploy/run.sh
