/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef config_service_CONSTANTS_H
#define config_service_CONSTANTS_H

#include "config_service_types.h"



class config_serviceConstants {
 public:
  config_serviceConstants();

};

extern const config_serviceConstants g_config_service_constants;



#endif
