#!/bin/sh
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/meituan/apps/cplugin/libs
export LD_LIBRARY_PATH

ulimit -n 1000000

cd /opt/meituan/apps/cplugin

PID=`cat /opt/meituan/apps/cplugin/cplugin.pid`

CMDLINE=`cat /proc/${PID}/cmdline`

if [ "${CMDLINE}"x == "/opt/meituan/apps/cplugin/cplugin"x ]
then
   echo "have alreadly run cplugin"
else
   exec setuidgid sankuai /opt/meituan/apps/cplugin/cplugin > /dev/null 2>&1
fi