namespace java com.sankuai.octo.logcollector.thrift.service
include  "oldlog.idl"
include  "log.idl"

service SGAgent
{
    i32 uploadCommonLog(1:log.CommonLog log);

    i32 uploadModuleInvoke(1:oldlog.SGModuleInvokeInfo oInfo);
}
