/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef config_service_TYPES_H
#define config_service_TYPES_H

#include <Thrift.h>
#include <TApplicationException.h>
#include <protocol/TProtocol.h>
#include <transport/TTransport.h>

#include "config_common_types.h"
#include "config_data_types.h"




typedef class  ::ConfigDataResponse ConfigDataResponse;

typedef class  ::GetMergeDataRequest GetMergeDataRequest;

typedef class  ::ConfigNode ConfigNode;

typedef class  ::DefaultConfigResponse DefaultConfigResponse;

typedef class  ::file_param_t file_param_t;

typedef class  ::ConfigFileRequest ConfigFileRequest;

typedef class  ::ConfigFileResponse ConfigFileResponse;

typedef class  ::ConfigGroupResponse ConfigGroupResponse;

typedef class  ::ConfigGroupsResponse ConfigGroupsResponse;

typedef class  ::PullRequest PullRequest;

typedef class  ::PRDetail PRDetail;

typedef class  ::Review Review;

typedef class  ::UpdateGroupRequest UpdateGroupRequest;

typedef class  ::FilelogRequest FilelogRequest;

typedef class  ::DeleteFileRequest DeleteFileRequest;

typedef class  ::FileConfigSyncRequest FileConfigSyncRequest;

typedef class  ::FileConfigSyncResponse FileConfigSyncResponse;

typedef class  ::SetConfigRequest SetConfigRequest;

typedef class  ::SetConfigResponse SetConfigResponse;



#endif
