/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef MNSCacheService_H
#define MNSCacheService_H

#include <TProcessor.h>
#include "mnsc_service_types.h"



class MNSCacheServiceIf {
 public:
  virtual ~MNSCacheServiceIf() {}
  virtual void getMNSCache(MNSResponse& _return, const std::string& appkey, const std::string& version, const std::string& env) = 0;
  virtual void getMNSCache4HLB(MNSResponse& _return, const std::string& appkey, const std::string& version, const std::string& env) = 0;
  virtual void getMNSCacheWithVersionCheck(MNSResponse& _return, const MnsRequest& req) = 0;
  virtual void getMNSCacheByAppkeys(MNSBatchResponse& _return, const std::vector<std::string> & appkeys, const std::string& protocol) = 0;
  virtual void getAppKeyListByBusinessLine(AppKeyListResponse& _return, const int32_t bizCode, const std::string& env) = 0;
  virtual void getHttpPropertiesByBusinessLine(HttpPropertiesResponse& _return, const int32_t bizCode, const std::string& env) = 0;
  virtual void getHttpPropertiesByAppkey(HttpPropertiesResponse& _return, const std::string& appkey, const std::string& env) = 0;
  virtual void getGroupsByAppkey(HttpGroupResponse& _return, const std::string& appkey, const std::string& env) = 0;
  virtual void getAllGroups(AllHttpGroupsResponse& _return, const std::string& env) = 0;
  virtual void getSandbox(SandboxResponse& _return, const std::string& appkey, const std::string& env) = 0;
  virtual bool saveSandbox(const std::string& id, const std::string& env, const std::string& data) = 0;
  virtual bool deleteSandbox(const std::string& id, const std::string& env) = 0;
  virtual void getSandboxConfig(std::vector<SandboxConfig> & _return, const std::vector<std::string> & appkeys, const std::string& env) = 0;
  virtual void getProvidersByIP(MNSResponse& _return, const std::string& ip) = 0;
  virtual bool delProvider(const std::string& appkey, const int32_t env, const int32_t serverType, const std::string& ip, const int32_t port) = 0;
  virtual void getAppkeyListByIP(AppKeyListResponse& _return, const std::string& ip) = 0;
  virtual void registerService(RegisterResponse& _return, const SGService& registerInfo) = 0;
};

class MNSCacheServiceIfFactory {
 public:
  typedef MNSCacheServiceIf Handler;

  virtual ~MNSCacheServiceIfFactory() {}

  virtual MNSCacheServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(MNSCacheServiceIf* /* handler */) = 0;
};

class MNSCacheServiceIfSingletonFactory : virtual public MNSCacheServiceIfFactory {
 public:
  MNSCacheServiceIfSingletonFactory(const boost::shared_ptr<MNSCacheServiceIf>& iface) : iface_(iface) {}
  virtual ~MNSCacheServiceIfSingletonFactory() {}

  virtual MNSCacheServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(MNSCacheServiceIf* /* handler */) {}

 protected:
  boost::shared_ptr<MNSCacheServiceIf> iface_;
};

class MNSCacheServiceNull : virtual public MNSCacheServiceIf {
 public:
  virtual ~MNSCacheServiceNull() {}
  void getMNSCache(MNSResponse& /* _return */, const std::string& /* appkey */, const std::string& /* version */, const std::string& /* env */) {
    return;
  }
  void getMNSCache4HLB(MNSResponse& /* _return */, const std::string& /* appkey */, const std::string& /* version */, const std::string& /* env */) {
    return;
  }
  void getMNSCacheWithVersionCheck(MNSResponse& /* _return */, const MnsRequest& /* req */) {
    return;
  }
  void getMNSCacheByAppkeys(MNSBatchResponse& /* _return */, const std::vector<std::string> & /* appkeys */, const std::string& /* protocol */) {
    return;
  }
  void getAppKeyListByBusinessLine(AppKeyListResponse& /* _return */, const int32_t /* bizCode */, const std::string& /* env */) {
    return;
  }
  void getHttpPropertiesByBusinessLine(HttpPropertiesResponse& /* _return */, const int32_t /* bizCode */, const std::string& /* env */) {
    return;
  }
  void getHttpPropertiesByAppkey(HttpPropertiesResponse& /* _return */, const std::string& /* appkey */, const std::string& /* env */) {
    return;
  }
  void getGroupsByAppkey(HttpGroupResponse& /* _return */, const std::string& /* appkey */, const std::string& /* env */) {
    return;
  }
  void getAllGroups(AllHttpGroupsResponse& /* _return */, const std::string& /* env */) {
    return;
  }
  void getSandbox(SandboxResponse& /* _return */, const std::string& /* appkey */, const std::string& /* env */) {
    return;
  }
  bool saveSandbox(const std::string& /* id */, const std::string& /* env */, const std::string& /* data */) {
    bool _return = false;
    return _return;
  }
  bool deleteSandbox(const std::string& /* id */, const std::string& /* env */) {
    bool _return = false;
    return _return;
  }
  void getSandboxConfig(std::vector<SandboxConfig> & /* _return */, const std::vector<std::string> & /* appkeys */, const std::string& /* env */) {
    return;
  }
  void getProvidersByIP(MNSResponse& /* _return */, const std::string& /* ip */) {
    return;
  }
  bool delProvider(const std::string& /* appkey */, const int32_t /* env */, const int32_t /* serverType */, const std::string& /* ip */, const int32_t /* port */) {
    bool _return = false;
    return _return;
  }
  void getAppkeyListByIP(AppKeyListResponse& /* _return */, const std::string& /* ip */) {
    return;
  }
  void registerService(RegisterResponse& /* _return */, const SGService& /* registerInfo */) {
    return;
  }
};

typedef struct _MNSCacheService_getMNSCache_args__isset {
  _MNSCacheService_getMNSCache_args__isset() : appkey(false), version(false), env(false) {}
  bool appkey;
  bool version;
  bool env;
} _MNSCacheService_getMNSCache_args__isset;

class MNSCacheService_getMNSCache_args {
 public:

  MNSCacheService_getMNSCache_args() : appkey(""), version(""), env("") {
  }

  virtual ~MNSCacheService_getMNSCache_args() throw() {}

  std::string appkey;
  std::string version;
  std::string env;

  _MNSCacheService_getMNSCache_args__isset __isset;

  void __set_appkey(const std::string& val) {
    appkey = val;
  }

  void __set_version(const std::string& val) {
    version = val;
  }

  void __set_env(const std::string& val) {
    env = val;
  }

  bool operator == (const MNSCacheService_getMNSCache_args & rhs) const
  {
    if (!(appkey == rhs.appkey))
      return false;
    if (!(version == rhs.version))
      return false;
    if (!(env == rhs.env))
      return false;
    return true;
  }
  bool operator != (const MNSCacheService_getMNSCache_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MNSCacheService_getMNSCache_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MNSCacheService_getMNSCache_pargs {
 public:


  virtual ~MNSCacheService_getMNSCache_pargs() throw() {}

  const std::string* appkey;
  const std::string* version;
  const std::string* env;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MNSCacheService_getMNSCache_result__isset {
  _MNSCacheService_getMNSCache_result__isset() : success(false) {}
  bool success;
} _MNSCacheService_getMNSCache_result__isset;

class MNSCacheService_getMNSCache_result {
 public:

  MNSCacheService_getMNSCache_result() {
  }

  virtual ~MNSCacheService_getMNSCache_result() throw() {}

  MNSResponse success;

  _MNSCacheService_getMNSCache_result__isset __isset;

  void __set_success(const MNSResponse& val) {
    success = val;
  }

  bool operator == (const MNSCacheService_getMNSCache_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const MNSCacheService_getMNSCache_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MNSCacheService_getMNSCache_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MNSCacheService_getMNSCache_presult__isset {
  _MNSCacheService_getMNSCache_presult__isset() : success(false) {}
  bool success;
} _MNSCacheService_getMNSCache_presult__isset;

class MNSCacheService_getMNSCache_presult {
 public:


  virtual ~MNSCacheService_getMNSCache_presult() throw() {}

  MNSResponse* success;

  _MNSCacheService_getMNSCache_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _MNSCacheService_getMNSCache4HLB_args__isset {
  _MNSCacheService_getMNSCache4HLB_args__isset() : appkey(false), version(false), env(false) {}
  bool appkey;
  bool version;
  bool env;
} _MNSCacheService_getMNSCache4HLB_args__isset;

class MNSCacheService_getMNSCache4HLB_args {
 public:

  MNSCacheService_getMNSCache4HLB_args() : appkey(""), version(""), env("") {
  }

  virtual ~MNSCacheService_getMNSCache4HLB_args() throw() {}

  std::string appkey;
  std::string version;
  std::string env;

  _MNSCacheService_getMNSCache4HLB_args__isset __isset;

  void __set_appkey(const std::string& val) {
    appkey = val;
  }

  void __set_version(const std::string& val) {
    version = val;
  }

  void __set_env(const std::string& val) {
    env = val;
  }

  bool operator == (const MNSCacheService_getMNSCache4HLB_args & rhs) const
  {
    if (!(appkey == rhs.appkey))
      return false;
    if (!(version == rhs.version))
      return false;
    if (!(env == rhs.env))
      return false;
    return true;
  }
  bool operator != (const MNSCacheService_getMNSCache4HLB_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MNSCacheService_getMNSCache4HLB_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MNSCacheService_getMNSCache4HLB_pargs {
 public:


  virtual ~MNSCacheService_getMNSCache4HLB_pargs() throw() {}

  const std::string* appkey;
  const std::string* version;
  const std::string* env;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MNSCacheService_getMNSCache4HLB_result__isset {
  _MNSCacheService_getMNSCache4HLB_result__isset() : success(false) {}
  bool success;
} _MNSCacheService_getMNSCache4HLB_result__isset;

class MNSCacheService_getMNSCache4HLB_result {
 public:

  MNSCacheService_getMNSCache4HLB_result() {
  }

  virtual ~MNSCacheService_getMNSCache4HLB_result() throw() {}

  MNSResponse success;

  _MNSCacheService_getMNSCache4HLB_result__isset __isset;

  void __set_success(const MNSResponse& val) {
    success = val;
  }

  bool operator == (const MNSCacheService_getMNSCache4HLB_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const MNSCacheService_getMNSCache4HLB_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MNSCacheService_getMNSCache4HLB_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MNSCacheService_getMNSCache4HLB_presult__isset {
  _MNSCacheService_getMNSCache4HLB_presult__isset() : success(false) {}
  bool success;
} _MNSCacheService_getMNSCache4HLB_presult__isset;

class MNSCacheService_getMNSCache4HLB_presult {
 public:


  virtual ~MNSCacheService_getMNSCache4HLB_presult() throw() {}

  MNSResponse* success;

  _MNSCacheService_getMNSCache4HLB_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _MNSCacheService_getMNSCacheWithVersionCheck_args__isset {
  _MNSCacheService_getMNSCacheWithVersionCheck_args__isset() : req(false) {}
  bool req;
} _MNSCacheService_getMNSCacheWithVersionCheck_args__isset;

class MNSCacheService_getMNSCacheWithVersionCheck_args {
 public:

  MNSCacheService_getMNSCacheWithVersionCheck_args() {
  }

  virtual ~MNSCacheService_getMNSCacheWithVersionCheck_args() throw() {}

  MnsRequest req;

  _MNSCacheService_getMNSCacheWithVersionCheck_args__isset __isset;

  void __set_req(const MnsRequest& val) {
    req = val;
  }

  bool operator == (const MNSCacheService_getMNSCacheWithVersionCheck_args & rhs) const
  {
    if (!(req == rhs.req))
      return false;
    return true;
  }
  bool operator != (const MNSCacheService_getMNSCacheWithVersionCheck_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MNSCacheService_getMNSCacheWithVersionCheck_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MNSCacheService_getMNSCacheWithVersionCheck_pargs {
 public:


  virtual ~MNSCacheService_getMNSCacheWithVersionCheck_pargs() throw() {}

  const MnsRequest* req;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MNSCacheService_getMNSCacheWithVersionCheck_result__isset {
  _MNSCacheService_getMNSCacheWithVersionCheck_result__isset() : success(false) {}
  bool success;
} _MNSCacheService_getMNSCacheWithVersionCheck_result__isset;

class MNSCacheService_getMNSCacheWithVersionCheck_result {
 public:

  MNSCacheService_getMNSCacheWithVersionCheck_result() {
  }

  virtual ~MNSCacheService_getMNSCacheWithVersionCheck_result() throw() {}

  MNSResponse success;

  _MNSCacheService_getMNSCacheWithVersionCheck_result__isset __isset;

  void __set_success(const MNSResponse& val) {
    success = val;
  }

  bool operator == (const MNSCacheService_getMNSCacheWithVersionCheck_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const MNSCacheService_getMNSCacheWithVersionCheck_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MNSCacheService_getMNSCacheWithVersionCheck_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MNSCacheService_getMNSCacheWithVersionCheck_presult__isset {
  _MNSCacheService_getMNSCacheWithVersionCheck_presult__isset() : success(false) {}
  bool success;
} _MNSCacheService_getMNSCacheWithVersionCheck_presult__isset;

class MNSCacheService_getMNSCacheWithVersionCheck_presult {
 public:


  virtual ~MNSCacheService_getMNSCacheWithVersionCheck_presult() throw() {}

  MNSResponse* success;

  _MNSCacheService_getMNSCacheWithVersionCheck_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _MNSCacheService_getMNSCacheByAppkeys_args__isset {
  _MNSCacheService_getMNSCacheByAppkeys_args__isset() : appkeys(false), protocol(false) {}
  bool appkeys;
  bool protocol;
} _MNSCacheService_getMNSCacheByAppkeys_args__isset;

class MNSCacheService_getMNSCacheByAppkeys_args {
 public:

  MNSCacheService_getMNSCacheByAppkeys_args() : protocol("") {
  }

  virtual ~MNSCacheService_getMNSCacheByAppkeys_args() throw() {}

  std::vector<std::string>  appkeys;
  std::string protocol;

  _MNSCacheService_getMNSCacheByAppkeys_args__isset __isset;

  void __set_appkeys(const std::vector<std::string> & val) {
    appkeys = val;
  }

  void __set_protocol(const std::string& val) {
    protocol = val;
  }

  bool operator == (const MNSCacheService_getMNSCacheByAppkeys_args & rhs) const
  {
    if (!(appkeys == rhs.appkeys))
      return false;
    if (!(protocol == rhs.protocol))
      return false;
    return true;
  }
  bool operator != (const MNSCacheService_getMNSCacheByAppkeys_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MNSCacheService_getMNSCacheByAppkeys_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MNSCacheService_getMNSCacheByAppkeys_pargs {
 public:


  virtual ~MNSCacheService_getMNSCacheByAppkeys_pargs() throw() {}

  const std::vector<std::string> * appkeys;
  const std::string* protocol;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MNSCacheService_getMNSCacheByAppkeys_result__isset {
  _MNSCacheService_getMNSCacheByAppkeys_result__isset() : success(false) {}
  bool success;
} _MNSCacheService_getMNSCacheByAppkeys_result__isset;

class MNSCacheService_getMNSCacheByAppkeys_result {
 public:

  MNSCacheService_getMNSCacheByAppkeys_result() {
  }

  virtual ~MNSCacheService_getMNSCacheByAppkeys_result() throw() {}

  MNSBatchResponse success;

  _MNSCacheService_getMNSCacheByAppkeys_result__isset __isset;

  void __set_success(const MNSBatchResponse& val) {
    success = val;
  }

  bool operator == (const MNSCacheService_getMNSCacheByAppkeys_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const MNSCacheService_getMNSCacheByAppkeys_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MNSCacheService_getMNSCacheByAppkeys_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MNSCacheService_getMNSCacheByAppkeys_presult__isset {
  _MNSCacheService_getMNSCacheByAppkeys_presult__isset() : success(false) {}
  bool success;
} _MNSCacheService_getMNSCacheByAppkeys_presult__isset;

class MNSCacheService_getMNSCacheByAppkeys_presult {
 public:


  virtual ~MNSCacheService_getMNSCacheByAppkeys_presult() throw() {}

  MNSBatchResponse* success;

  _MNSCacheService_getMNSCacheByAppkeys_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _MNSCacheService_getAppKeyListByBusinessLine_args__isset {
  _MNSCacheService_getAppKeyListByBusinessLine_args__isset() : bizCode(false), env(false) {}
  bool bizCode;
  bool env;
} _MNSCacheService_getAppKeyListByBusinessLine_args__isset;

class MNSCacheService_getAppKeyListByBusinessLine_args {
 public:

  MNSCacheService_getAppKeyListByBusinessLine_args() : bizCode(0), env("") {
  }

  virtual ~MNSCacheService_getAppKeyListByBusinessLine_args() throw() {}

  int32_t bizCode;
  std::string env;

  _MNSCacheService_getAppKeyListByBusinessLine_args__isset __isset;

  void __set_bizCode(const int32_t val) {
    bizCode = val;
  }

  void __set_env(const std::string& val) {
    env = val;
  }

  bool operator == (const MNSCacheService_getAppKeyListByBusinessLine_args & rhs) const
  {
    if (!(bizCode == rhs.bizCode))
      return false;
    if (!(env == rhs.env))
      return false;
    return true;
  }
  bool operator != (const MNSCacheService_getAppKeyListByBusinessLine_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MNSCacheService_getAppKeyListByBusinessLine_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MNSCacheService_getAppKeyListByBusinessLine_pargs {
 public:


  virtual ~MNSCacheService_getAppKeyListByBusinessLine_pargs() throw() {}

  const int32_t* bizCode;
  const std::string* env;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MNSCacheService_getAppKeyListByBusinessLine_result__isset {
  _MNSCacheService_getAppKeyListByBusinessLine_result__isset() : success(false) {}
  bool success;
} _MNSCacheService_getAppKeyListByBusinessLine_result__isset;

class MNSCacheService_getAppKeyListByBusinessLine_result {
 public:

  MNSCacheService_getAppKeyListByBusinessLine_result() {
  }

  virtual ~MNSCacheService_getAppKeyListByBusinessLine_result() throw() {}

  AppKeyListResponse success;

  _MNSCacheService_getAppKeyListByBusinessLine_result__isset __isset;

  void __set_success(const AppKeyListResponse& val) {
    success = val;
  }

  bool operator == (const MNSCacheService_getAppKeyListByBusinessLine_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const MNSCacheService_getAppKeyListByBusinessLine_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MNSCacheService_getAppKeyListByBusinessLine_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MNSCacheService_getAppKeyListByBusinessLine_presult__isset {
  _MNSCacheService_getAppKeyListByBusinessLine_presult__isset() : success(false) {}
  bool success;
} _MNSCacheService_getAppKeyListByBusinessLine_presult__isset;

class MNSCacheService_getAppKeyListByBusinessLine_presult {
 public:


  virtual ~MNSCacheService_getAppKeyListByBusinessLine_presult() throw() {}

  AppKeyListResponse* success;

  _MNSCacheService_getAppKeyListByBusinessLine_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _MNSCacheService_getHttpPropertiesByBusinessLine_args__isset {
  _MNSCacheService_getHttpPropertiesByBusinessLine_args__isset() : bizCode(false), env(false) {}
  bool bizCode;
  bool env;
} _MNSCacheService_getHttpPropertiesByBusinessLine_args__isset;

class MNSCacheService_getHttpPropertiesByBusinessLine_args {
 public:

  MNSCacheService_getHttpPropertiesByBusinessLine_args() : bizCode(0), env("") {
  }

  virtual ~MNSCacheService_getHttpPropertiesByBusinessLine_args() throw() {}

  int32_t bizCode;
  std::string env;

  _MNSCacheService_getHttpPropertiesByBusinessLine_args__isset __isset;

  void __set_bizCode(const int32_t val) {
    bizCode = val;
  }

  void __set_env(const std::string& val) {
    env = val;
  }

  bool operator == (const MNSCacheService_getHttpPropertiesByBusinessLine_args & rhs) const
  {
    if (!(bizCode == rhs.bizCode))
      return false;
    if (!(env == rhs.env))
      return false;
    return true;
  }
  bool operator != (const MNSCacheService_getHttpPropertiesByBusinessLine_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MNSCacheService_getHttpPropertiesByBusinessLine_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MNSCacheService_getHttpPropertiesByBusinessLine_pargs {
 public:


  virtual ~MNSCacheService_getHttpPropertiesByBusinessLine_pargs() throw() {}

  const int32_t* bizCode;
  const std::string* env;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MNSCacheService_getHttpPropertiesByBusinessLine_result__isset {
  _MNSCacheService_getHttpPropertiesByBusinessLine_result__isset() : success(false) {}
  bool success;
} _MNSCacheService_getHttpPropertiesByBusinessLine_result__isset;

class MNSCacheService_getHttpPropertiesByBusinessLine_result {
 public:

  MNSCacheService_getHttpPropertiesByBusinessLine_result() {
  }

  virtual ~MNSCacheService_getHttpPropertiesByBusinessLine_result() throw() {}

  HttpPropertiesResponse success;

  _MNSCacheService_getHttpPropertiesByBusinessLine_result__isset __isset;

  void __set_success(const HttpPropertiesResponse& val) {
    success = val;
  }

  bool operator == (const MNSCacheService_getHttpPropertiesByBusinessLine_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const MNSCacheService_getHttpPropertiesByBusinessLine_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MNSCacheService_getHttpPropertiesByBusinessLine_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MNSCacheService_getHttpPropertiesByBusinessLine_presult__isset {
  _MNSCacheService_getHttpPropertiesByBusinessLine_presult__isset() : success(false) {}
  bool success;
} _MNSCacheService_getHttpPropertiesByBusinessLine_presult__isset;

class MNSCacheService_getHttpPropertiesByBusinessLine_presult {
 public:


  virtual ~MNSCacheService_getHttpPropertiesByBusinessLine_presult() throw() {}

  HttpPropertiesResponse* success;

  _MNSCacheService_getHttpPropertiesByBusinessLine_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _MNSCacheService_getHttpPropertiesByAppkey_args__isset {
  _MNSCacheService_getHttpPropertiesByAppkey_args__isset() : appkey(false), env(false) {}
  bool appkey;
  bool env;
} _MNSCacheService_getHttpPropertiesByAppkey_args__isset;

class MNSCacheService_getHttpPropertiesByAppkey_args {
 public:

  MNSCacheService_getHttpPropertiesByAppkey_args() : appkey(""), env("") {
  }

  virtual ~MNSCacheService_getHttpPropertiesByAppkey_args() throw() {}

  std::string appkey;
  std::string env;

  _MNSCacheService_getHttpPropertiesByAppkey_args__isset __isset;

  void __set_appkey(const std::string& val) {
    appkey = val;
  }

  void __set_env(const std::string& val) {
    env = val;
  }

  bool operator == (const MNSCacheService_getHttpPropertiesByAppkey_args & rhs) const
  {
    if (!(appkey == rhs.appkey))
      return false;
    if (!(env == rhs.env))
      return false;
    return true;
  }
  bool operator != (const MNSCacheService_getHttpPropertiesByAppkey_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MNSCacheService_getHttpPropertiesByAppkey_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MNSCacheService_getHttpPropertiesByAppkey_pargs {
 public:


  virtual ~MNSCacheService_getHttpPropertiesByAppkey_pargs() throw() {}

  const std::string* appkey;
  const std::string* env;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MNSCacheService_getHttpPropertiesByAppkey_result__isset {
  _MNSCacheService_getHttpPropertiesByAppkey_result__isset() : success(false) {}
  bool success;
} _MNSCacheService_getHttpPropertiesByAppkey_result__isset;

class MNSCacheService_getHttpPropertiesByAppkey_result {
 public:

  MNSCacheService_getHttpPropertiesByAppkey_result() {
  }

  virtual ~MNSCacheService_getHttpPropertiesByAppkey_result() throw() {}

  HttpPropertiesResponse success;

  _MNSCacheService_getHttpPropertiesByAppkey_result__isset __isset;

  void __set_success(const HttpPropertiesResponse& val) {
    success = val;
  }

  bool operator == (const MNSCacheService_getHttpPropertiesByAppkey_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const MNSCacheService_getHttpPropertiesByAppkey_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MNSCacheService_getHttpPropertiesByAppkey_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MNSCacheService_getHttpPropertiesByAppkey_presult__isset {
  _MNSCacheService_getHttpPropertiesByAppkey_presult__isset() : success(false) {}
  bool success;
} _MNSCacheService_getHttpPropertiesByAppkey_presult__isset;

class MNSCacheService_getHttpPropertiesByAppkey_presult {
 public:


  virtual ~MNSCacheService_getHttpPropertiesByAppkey_presult() throw() {}

  HttpPropertiesResponse* success;

  _MNSCacheService_getHttpPropertiesByAppkey_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _MNSCacheService_getGroupsByAppkey_args__isset {
  _MNSCacheService_getGroupsByAppkey_args__isset() : appkey(false), env(false) {}
  bool appkey;
  bool env;
} _MNSCacheService_getGroupsByAppkey_args__isset;

class MNSCacheService_getGroupsByAppkey_args {
 public:

  MNSCacheService_getGroupsByAppkey_args() : appkey(""), env("") {
  }

  virtual ~MNSCacheService_getGroupsByAppkey_args() throw() {}

  std::string appkey;
  std::string env;

  _MNSCacheService_getGroupsByAppkey_args__isset __isset;

  void __set_appkey(const std::string& val) {
    appkey = val;
  }

  void __set_env(const std::string& val) {
    env = val;
  }

  bool operator == (const MNSCacheService_getGroupsByAppkey_args & rhs) const
  {
    if (!(appkey == rhs.appkey))
      return false;
    if (!(env == rhs.env))
      return false;
    return true;
  }
  bool operator != (const MNSCacheService_getGroupsByAppkey_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MNSCacheService_getGroupsByAppkey_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MNSCacheService_getGroupsByAppkey_pargs {
 public:


  virtual ~MNSCacheService_getGroupsByAppkey_pargs() throw() {}

  const std::string* appkey;
  const std::string* env;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MNSCacheService_getGroupsByAppkey_result__isset {
  _MNSCacheService_getGroupsByAppkey_result__isset() : success(false) {}
  bool success;
} _MNSCacheService_getGroupsByAppkey_result__isset;

class MNSCacheService_getGroupsByAppkey_result {
 public:

  MNSCacheService_getGroupsByAppkey_result() {
  }

  virtual ~MNSCacheService_getGroupsByAppkey_result() throw() {}

  HttpGroupResponse success;

  _MNSCacheService_getGroupsByAppkey_result__isset __isset;

  void __set_success(const HttpGroupResponse& val) {
    success = val;
  }

  bool operator == (const MNSCacheService_getGroupsByAppkey_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const MNSCacheService_getGroupsByAppkey_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MNSCacheService_getGroupsByAppkey_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MNSCacheService_getGroupsByAppkey_presult__isset {
  _MNSCacheService_getGroupsByAppkey_presult__isset() : success(false) {}
  bool success;
} _MNSCacheService_getGroupsByAppkey_presult__isset;

class MNSCacheService_getGroupsByAppkey_presult {
 public:


  virtual ~MNSCacheService_getGroupsByAppkey_presult() throw() {}

  HttpGroupResponse* success;

  _MNSCacheService_getGroupsByAppkey_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _MNSCacheService_getAllGroups_args__isset {
  _MNSCacheService_getAllGroups_args__isset() : env(false) {}
  bool env;
} _MNSCacheService_getAllGroups_args__isset;

class MNSCacheService_getAllGroups_args {
 public:

  MNSCacheService_getAllGroups_args() : env("") {
  }

  virtual ~MNSCacheService_getAllGroups_args() throw() {}

  std::string env;

  _MNSCacheService_getAllGroups_args__isset __isset;

  void __set_env(const std::string& val) {
    env = val;
  }

  bool operator == (const MNSCacheService_getAllGroups_args & rhs) const
  {
    if (!(env == rhs.env))
      return false;
    return true;
  }
  bool operator != (const MNSCacheService_getAllGroups_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MNSCacheService_getAllGroups_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MNSCacheService_getAllGroups_pargs {
 public:


  virtual ~MNSCacheService_getAllGroups_pargs() throw() {}

  const std::string* env;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MNSCacheService_getAllGroups_result__isset {
  _MNSCacheService_getAllGroups_result__isset() : success(false) {}
  bool success;
} _MNSCacheService_getAllGroups_result__isset;

class MNSCacheService_getAllGroups_result {
 public:

  MNSCacheService_getAllGroups_result() {
  }

  virtual ~MNSCacheService_getAllGroups_result() throw() {}

  AllHttpGroupsResponse success;

  _MNSCacheService_getAllGroups_result__isset __isset;

  void __set_success(const AllHttpGroupsResponse& val) {
    success = val;
  }

  bool operator == (const MNSCacheService_getAllGroups_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const MNSCacheService_getAllGroups_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MNSCacheService_getAllGroups_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MNSCacheService_getAllGroups_presult__isset {
  _MNSCacheService_getAllGroups_presult__isset() : success(false) {}
  bool success;
} _MNSCacheService_getAllGroups_presult__isset;

class MNSCacheService_getAllGroups_presult {
 public:


  virtual ~MNSCacheService_getAllGroups_presult() throw() {}

  AllHttpGroupsResponse* success;

  _MNSCacheService_getAllGroups_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _MNSCacheService_getSandbox_args__isset {
  _MNSCacheService_getSandbox_args__isset() : appkey(false), env(false) {}
  bool appkey;
  bool env;
} _MNSCacheService_getSandbox_args__isset;

class MNSCacheService_getSandbox_args {
 public:

  MNSCacheService_getSandbox_args() : appkey(""), env("") {
  }

  virtual ~MNSCacheService_getSandbox_args() throw() {}

  std::string appkey;
  std::string env;

  _MNSCacheService_getSandbox_args__isset __isset;

  void __set_appkey(const std::string& val) {
    appkey = val;
  }

  void __set_env(const std::string& val) {
    env = val;
  }

  bool operator == (const MNSCacheService_getSandbox_args & rhs) const
  {
    if (!(appkey == rhs.appkey))
      return false;
    if (!(env == rhs.env))
      return false;
    return true;
  }
  bool operator != (const MNSCacheService_getSandbox_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MNSCacheService_getSandbox_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MNSCacheService_getSandbox_pargs {
 public:


  virtual ~MNSCacheService_getSandbox_pargs() throw() {}

  const std::string* appkey;
  const std::string* env;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MNSCacheService_getSandbox_result__isset {
  _MNSCacheService_getSandbox_result__isset() : success(false) {}
  bool success;
} _MNSCacheService_getSandbox_result__isset;

class MNSCacheService_getSandbox_result {
 public:

  MNSCacheService_getSandbox_result() {
  }

  virtual ~MNSCacheService_getSandbox_result() throw() {}

  SandboxResponse success;

  _MNSCacheService_getSandbox_result__isset __isset;

  void __set_success(const SandboxResponse& val) {
    success = val;
  }

  bool operator == (const MNSCacheService_getSandbox_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const MNSCacheService_getSandbox_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MNSCacheService_getSandbox_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MNSCacheService_getSandbox_presult__isset {
  _MNSCacheService_getSandbox_presult__isset() : success(false) {}
  bool success;
} _MNSCacheService_getSandbox_presult__isset;

class MNSCacheService_getSandbox_presult {
 public:


  virtual ~MNSCacheService_getSandbox_presult() throw() {}

  SandboxResponse* success;

  _MNSCacheService_getSandbox_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _MNSCacheService_saveSandbox_args__isset {
  _MNSCacheService_saveSandbox_args__isset() : id(false), env(false), data(false) {}
  bool id;
  bool env;
  bool data;
} _MNSCacheService_saveSandbox_args__isset;

class MNSCacheService_saveSandbox_args {
 public:

  MNSCacheService_saveSandbox_args() : id(""), env(""), data("") {
  }

  virtual ~MNSCacheService_saveSandbox_args() throw() {}

  std::string id;
  std::string env;
  std::string data;

  _MNSCacheService_saveSandbox_args__isset __isset;

  void __set_id(const std::string& val) {
    id = val;
  }

  void __set_env(const std::string& val) {
    env = val;
  }

  void __set_data(const std::string& val) {
    data = val;
  }

  bool operator == (const MNSCacheService_saveSandbox_args & rhs) const
  {
    if (!(id == rhs.id))
      return false;
    if (!(env == rhs.env))
      return false;
    if (!(data == rhs.data))
      return false;
    return true;
  }
  bool operator != (const MNSCacheService_saveSandbox_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MNSCacheService_saveSandbox_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MNSCacheService_saveSandbox_pargs {
 public:


  virtual ~MNSCacheService_saveSandbox_pargs() throw() {}

  const std::string* id;
  const std::string* env;
  const std::string* data;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MNSCacheService_saveSandbox_result__isset {
  _MNSCacheService_saveSandbox_result__isset() : success(false) {}
  bool success;
} _MNSCacheService_saveSandbox_result__isset;

class MNSCacheService_saveSandbox_result {
 public:

  MNSCacheService_saveSandbox_result() : success(0) {
  }

  virtual ~MNSCacheService_saveSandbox_result() throw() {}

  bool success;

  _MNSCacheService_saveSandbox_result__isset __isset;

  void __set_success(const bool val) {
    success = val;
  }

  bool operator == (const MNSCacheService_saveSandbox_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const MNSCacheService_saveSandbox_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MNSCacheService_saveSandbox_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MNSCacheService_saveSandbox_presult__isset {
  _MNSCacheService_saveSandbox_presult__isset() : success(false) {}
  bool success;
} _MNSCacheService_saveSandbox_presult__isset;

class MNSCacheService_saveSandbox_presult {
 public:


  virtual ~MNSCacheService_saveSandbox_presult() throw() {}

  bool* success;

  _MNSCacheService_saveSandbox_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _MNSCacheService_deleteSandbox_args__isset {
  _MNSCacheService_deleteSandbox_args__isset() : id(false), env(false) {}
  bool id;
  bool env;
} _MNSCacheService_deleteSandbox_args__isset;

class MNSCacheService_deleteSandbox_args {
 public:

  MNSCacheService_deleteSandbox_args() : id(""), env("") {
  }

  virtual ~MNSCacheService_deleteSandbox_args() throw() {}

  std::string id;
  std::string env;

  _MNSCacheService_deleteSandbox_args__isset __isset;

  void __set_id(const std::string& val) {
    id = val;
  }

  void __set_env(const std::string& val) {
    env = val;
  }

  bool operator == (const MNSCacheService_deleteSandbox_args & rhs) const
  {
    if (!(id == rhs.id))
      return false;
    if (!(env == rhs.env))
      return false;
    return true;
  }
  bool operator != (const MNSCacheService_deleteSandbox_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MNSCacheService_deleteSandbox_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MNSCacheService_deleteSandbox_pargs {
 public:


  virtual ~MNSCacheService_deleteSandbox_pargs() throw() {}

  const std::string* id;
  const std::string* env;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MNSCacheService_deleteSandbox_result__isset {
  _MNSCacheService_deleteSandbox_result__isset() : success(false) {}
  bool success;
} _MNSCacheService_deleteSandbox_result__isset;

class MNSCacheService_deleteSandbox_result {
 public:

  MNSCacheService_deleteSandbox_result() : success(0) {
  }

  virtual ~MNSCacheService_deleteSandbox_result() throw() {}

  bool success;

  _MNSCacheService_deleteSandbox_result__isset __isset;

  void __set_success(const bool val) {
    success = val;
  }

  bool operator == (const MNSCacheService_deleteSandbox_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const MNSCacheService_deleteSandbox_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MNSCacheService_deleteSandbox_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MNSCacheService_deleteSandbox_presult__isset {
  _MNSCacheService_deleteSandbox_presult__isset() : success(false) {}
  bool success;
} _MNSCacheService_deleteSandbox_presult__isset;

class MNSCacheService_deleteSandbox_presult {
 public:


  virtual ~MNSCacheService_deleteSandbox_presult() throw() {}

  bool* success;

  _MNSCacheService_deleteSandbox_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _MNSCacheService_getSandboxConfig_args__isset {
  _MNSCacheService_getSandboxConfig_args__isset() : appkeys(false), env(false) {}
  bool appkeys;
  bool env;
} _MNSCacheService_getSandboxConfig_args__isset;

class MNSCacheService_getSandboxConfig_args {
 public:

  MNSCacheService_getSandboxConfig_args() : env("") {
  }

  virtual ~MNSCacheService_getSandboxConfig_args() throw() {}

  std::vector<std::string>  appkeys;
  std::string env;

  _MNSCacheService_getSandboxConfig_args__isset __isset;

  void __set_appkeys(const std::vector<std::string> & val) {
    appkeys = val;
  }

  void __set_env(const std::string& val) {
    env = val;
  }

  bool operator == (const MNSCacheService_getSandboxConfig_args & rhs) const
  {
    if (!(appkeys == rhs.appkeys))
      return false;
    if (!(env == rhs.env))
      return false;
    return true;
  }
  bool operator != (const MNSCacheService_getSandboxConfig_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MNSCacheService_getSandboxConfig_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MNSCacheService_getSandboxConfig_pargs {
 public:


  virtual ~MNSCacheService_getSandboxConfig_pargs() throw() {}

  const std::vector<std::string> * appkeys;
  const std::string* env;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MNSCacheService_getSandboxConfig_result__isset {
  _MNSCacheService_getSandboxConfig_result__isset() : success(false) {}
  bool success;
} _MNSCacheService_getSandboxConfig_result__isset;

class MNSCacheService_getSandboxConfig_result {
 public:

  MNSCacheService_getSandboxConfig_result() {
  }

  virtual ~MNSCacheService_getSandboxConfig_result() throw() {}

  std::vector<SandboxConfig>  success;

  _MNSCacheService_getSandboxConfig_result__isset __isset;

  void __set_success(const std::vector<SandboxConfig> & val) {
    success = val;
  }

  bool operator == (const MNSCacheService_getSandboxConfig_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const MNSCacheService_getSandboxConfig_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MNSCacheService_getSandboxConfig_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MNSCacheService_getSandboxConfig_presult__isset {
  _MNSCacheService_getSandboxConfig_presult__isset() : success(false) {}
  bool success;
} _MNSCacheService_getSandboxConfig_presult__isset;

class MNSCacheService_getSandboxConfig_presult {
 public:


  virtual ~MNSCacheService_getSandboxConfig_presult() throw() {}

  std::vector<SandboxConfig> * success;

  _MNSCacheService_getSandboxConfig_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _MNSCacheService_getProvidersByIP_args__isset {
  _MNSCacheService_getProvidersByIP_args__isset() : ip(false) {}
  bool ip;
} _MNSCacheService_getProvidersByIP_args__isset;

class MNSCacheService_getProvidersByIP_args {
 public:

  MNSCacheService_getProvidersByIP_args() : ip("") {
  }

  virtual ~MNSCacheService_getProvidersByIP_args() throw() {}

  std::string ip;

  _MNSCacheService_getProvidersByIP_args__isset __isset;

  void __set_ip(const std::string& val) {
    ip = val;
  }

  bool operator == (const MNSCacheService_getProvidersByIP_args & rhs) const
  {
    if (!(ip == rhs.ip))
      return false;
    return true;
  }
  bool operator != (const MNSCacheService_getProvidersByIP_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MNSCacheService_getProvidersByIP_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MNSCacheService_getProvidersByIP_pargs {
 public:


  virtual ~MNSCacheService_getProvidersByIP_pargs() throw() {}

  const std::string* ip;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MNSCacheService_getProvidersByIP_result__isset {
  _MNSCacheService_getProvidersByIP_result__isset() : success(false) {}
  bool success;
} _MNSCacheService_getProvidersByIP_result__isset;

class MNSCacheService_getProvidersByIP_result {
 public:

  MNSCacheService_getProvidersByIP_result() {
  }

  virtual ~MNSCacheService_getProvidersByIP_result() throw() {}

  MNSResponse success;

  _MNSCacheService_getProvidersByIP_result__isset __isset;

  void __set_success(const MNSResponse& val) {
    success = val;
  }

  bool operator == (const MNSCacheService_getProvidersByIP_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const MNSCacheService_getProvidersByIP_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MNSCacheService_getProvidersByIP_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MNSCacheService_getProvidersByIP_presult__isset {
  _MNSCacheService_getProvidersByIP_presult__isset() : success(false) {}
  bool success;
} _MNSCacheService_getProvidersByIP_presult__isset;

class MNSCacheService_getProvidersByIP_presult {
 public:


  virtual ~MNSCacheService_getProvidersByIP_presult() throw() {}

  MNSResponse* success;

  _MNSCacheService_getProvidersByIP_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _MNSCacheService_delProvider_args__isset {
  _MNSCacheService_delProvider_args__isset() : appkey(false), env(false), serverType(false), ip(false), port(false) {}
  bool appkey;
  bool env;
  bool serverType;
  bool ip;
  bool port;
} _MNSCacheService_delProvider_args__isset;

class MNSCacheService_delProvider_args {
 public:

  MNSCacheService_delProvider_args() : appkey(""), env(0), serverType(0), ip(""), port(0) {
  }

  virtual ~MNSCacheService_delProvider_args() throw() {}

  std::string appkey;
  int32_t env;
  int32_t serverType;
  std::string ip;
  int32_t port;

  _MNSCacheService_delProvider_args__isset __isset;

  void __set_appkey(const std::string& val) {
    appkey = val;
  }

  void __set_env(const int32_t val) {
    env = val;
  }

  void __set_serverType(const int32_t val) {
    serverType = val;
  }

  void __set_ip(const std::string& val) {
    ip = val;
  }

  void __set_port(const int32_t val) {
    port = val;
  }

  bool operator == (const MNSCacheService_delProvider_args & rhs) const
  {
    if (!(appkey == rhs.appkey))
      return false;
    if (!(env == rhs.env))
      return false;
    if (!(serverType == rhs.serverType))
      return false;
    if (!(ip == rhs.ip))
      return false;
    if (!(port == rhs.port))
      return false;
    return true;
  }
  bool operator != (const MNSCacheService_delProvider_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MNSCacheService_delProvider_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MNSCacheService_delProvider_pargs {
 public:


  virtual ~MNSCacheService_delProvider_pargs() throw() {}

  const std::string* appkey;
  const int32_t* env;
  const int32_t* serverType;
  const std::string* ip;
  const int32_t* port;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MNSCacheService_delProvider_result__isset {
  _MNSCacheService_delProvider_result__isset() : success(false) {}
  bool success;
} _MNSCacheService_delProvider_result__isset;

class MNSCacheService_delProvider_result {
 public:

  MNSCacheService_delProvider_result() : success(0) {
  }

  virtual ~MNSCacheService_delProvider_result() throw() {}

  bool success;

  _MNSCacheService_delProvider_result__isset __isset;

  void __set_success(const bool val) {
    success = val;
  }

  bool operator == (const MNSCacheService_delProvider_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const MNSCacheService_delProvider_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MNSCacheService_delProvider_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MNSCacheService_delProvider_presult__isset {
  _MNSCacheService_delProvider_presult__isset() : success(false) {}
  bool success;
} _MNSCacheService_delProvider_presult__isset;

class MNSCacheService_delProvider_presult {
 public:


  virtual ~MNSCacheService_delProvider_presult() throw() {}

  bool* success;

  _MNSCacheService_delProvider_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _MNSCacheService_getAppkeyListByIP_args__isset {
  _MNSCacheService_getAppkeyListByIP_args__isset() : ip(false) {}
  bool ip;
} _MNSCacheService_getAppkeyListByIP_args__isset;

class MNSCacheService_getAppkeyListByIP_args {
 public:

  MNSCacheService_getAppkeyListByIP_args() : ip("") {
  }

  virtual ~MNSCacheService_getAppkeyListByIP_args() throw() {}

  std::string ip;

  _MNSCacheService_getAppkeyListByIP_args__isset __isset;

  void __set_ip(const std::string& val) {
    ip = val;
  }

  bool operator == (const MNSCacheService_getAppkeyListByIP_args & rhs) const
  {
    if (!(ip == rhs.ip))
      return false;
    return true;
  }
  bool operator != (const MNSCacheService_getAppkeyListByIP_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MNSCacheService_getAppkeyListByIP_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MNSCacheService_getAppkeyListByIP_pargs {
 public:


  virtual ~MNSCacheService_getAppkeyListByIP_pargs() throw() {}

  const std::string* ip;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MNSCacheService_getAppkeyListByIP_result__isset {
  _MNSCacheService_getAppkeyListByIP_result__isset() : success(false) {}
  bool success;
} _MNSCacheService_getAppkeyListByIP_result__isset;

class MNSCacheService_getAppkeyListByIP_result {
 public:

  MNSCacheService_getAppkeyListByIP_result() {
  }

  virtual ~MNSCacheService_getAppkeyListByIP_result() throw() {}

  AppKeyListResponse success;

  _MNSCacheService_getAppkeyListByIP_result__isset __isset;

  void __set_success(const AppKeyListResponse& val) {
    success = val;
  }

  bool operator == (const MNSCacheService_getAppkeyListByIP_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const MNSCacheService_getAppkeyListByIP_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MNSCacheService_getAppkeyListByIP_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MNSCacheService_getAppkeyListByIP_presult__isset {
  _MNSCacheService_getAppkeyListByIP_presult__isset() : success(false) {}
  bool success;
} _MNSCacheService_getAppkeyListByIP_presult__isset;

class MNSCacheService_getAppkeyListByIP_presult {
 public:


  virtual ~MNSCacheService_getAppkeyListByIP_presult() throw() {}

  AppKeyListResponse* success;

  _MNSCacheService_getAppkeyListByIP_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _MNSCacheService_registerService_args__isset {
  _MNSCacheService_registerService_args__isset() : registerInfo(false) {}
  bool registerInfo;
} _MNSCacheService_registerService_args__isset;

class MNSCacheService_registerService_args {
 public:

  MNSCacheService_registerService_args() {
  }

  virtual ~MNSCacheService_registerService_args() throw() {}

  SGService registerInfo;

  _MNSCacheService_registerService_args__isset __isset;

  void __set_registerInfo(const SGService& val) {
    registerInfo = val;
  }

  bool operator == (const MNSCacheService_registerService_args & rhs) const
  {
    if (!(registerInfo == rhs.registerInfo))
      return false;
    return true;
  }
  bool operator != (const MNSCacheService_registerService_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MNSCacheService_registerService_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MNSCacheService_registerService_pargs {
 public:


  virtual ~MNSCacheService_registerService_pargs() throw() {}

  const SGService* registerInfo;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MNSCacheService_registerService_result__isset {
  _MNSCacheService_registerService_result__isset() : success(false) {}
  bool success;
} _MNSCacheService_registerService_result__isset;

class MNSCacheService_registerService_result {
 public:

  MNSCacheService_registerService_result() {
  }

  virtual ~MNSCacheService_registerService_result() throw() {}

  RegisterResponse success;

  _MNSCacheService_registerService_result__isset __isset;

  void __set_success(const RegisterResponse& val) {
    success = val;
  }

  bool operator == (const MNSCacheService_registerService_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const MNSCacheService_registerService_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MNSCacheService_registerService_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MNSCacheService_registerService_presult__isset {
  _MNSCacheService_registerService_presult__isset() : success(false) {}
  bool success;
} _MNSCacheService_registerService_presult__isset;

class MNSCacheService_registerService_presult {
 public:


  virtual ~MNSCacheService_registerService_presult() throw() {}

  RegisterResponse* success;

  _MNSCacheService_registerService_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class MNSCacheServiceClient : virtual public MNSCacheServiceIf {
 public:
  MNSCacheServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  MNSCacheServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void getMNSCache(MNSResponse& _return, const std::string& appkey, const std::string& version, const std::string& env);
  void send_getMNSCache(const std::string& appkey, const std::string& version, const std::string& env);
  void recv_getMNSCache(MNSResponse& _return);
  void getMNSCache4HLB(MNSResponse& _return, const std::string& appkey, const std::string& version, const std::string& env);
  void send_getMNSCache4HLB(const std::string& appkey, const std::string& version, const std::string& env);
  void recv_getMNSCache4HLB(MNSResponse& _return);
  void getMNSCacheWithVersionCheck(MNSResponse& _return, const MnsRequest& req);
  void send_getMNSCacheWithVersionCheck(const MnsRequest& req);
  void recv_getMNSCacheWithVersionCheck(MNSResponse& _return);
  void getMNSCacheByAppkeys(MNSBatchResponse& _return, const std::vector<std::string> & appkeys, const std::string& protocol);
  void send_getMNSCacheByAppkeys(const std::vector<std::string> & appkeys, const std::string& protocol);
  void recv_getMNSCacheByAppkeys(MNSBatchResponse& _return);
  void getAppKeyListByBusinessLine(AppKeyListResponse& _return, const int32_t bizCode, const std::string& env);
  void send_getAppKeyListByBusinessLine(const int32_t bizCode, const std::string& env);
  void recv_getAppKeyListByBusinessLine(AppKeyListResponse& _return);
  void getHttpPropertiesByBusinessLine(HttpPropertiesResponse& _return, const int32_t bizCode, const std::string& env);
  void send_getHttpPropertiesByBusinessLine(const int32_t bizCode, const std::string& env);
  void recv_getHttpPropertiesByBusinessLine(HttpPropertiesResponse& _return);
  void getHttpPropertiesByAppkey(HttpPropertiesResponse& _return, const std::string& appkey, const std::string& env);
  void send_getHttpPropertiesByAppkey(const std::string& appkey, const std::string& env);
  void recv_getHttpPropertiesByAppkey(HttpPropertiesResponse& _return);
  void getGroupsByAppkey(HttpGroupResponse& _return, const std::string& appkey, const std::string& env);
  void send_getGroupsByAppkey(const std::string& appkey, const std::string& env);
  void recv_getGroupsByAppkey(HttpGroupResponse& _return);
  void getAllGroups(AllHttpGroupsResponse& _return, const std::string& env);
  void send_getAllGroups(const std::string& env);
  void recv_getAllGroups(AllHttpGroupsResponse& _return);
  void getSandbox(SandboxResponse& _return, const std::string& appkey, const std::string& env);
  void send_getSandbox(const std::string& appkey, const std::string& env);
  void recv_getSandbox(SandboxResponse& _return);
  bool saveSandbox(const std::string& id, const std::string& env, const std::string& data);
  void send_saveSandbox(const std::string& id, const std::string& env, const std::string& data);
  bool recv_saveSandbox();
  bool deleteSandbox(const std::string& id, const std::string& env);
  void send_deleteSandbox(const std::string& id, const std::string& env);
  bool recv_deleteSandbox();
  void getSandboxConfig(std::vector<SandboxConfig> & _return, const std::vector<std::string> & appkeys, const std::string& env);
  void send_getSandboxConfig(const std::vector<std::string> & appkeys, const std::string& env);
  void recv_getSandboxConfig(std::vector<SandboxConfig> & _return);
  void getProvidersByIP(MNSResponse& _return, const std::string& ip);
  void send_getProvidersByIP(const std::string& ip);
  void recv_getProvidersByIP(MNSResponse& _return);
  bool delProvider(const std::string& appkey, const int32_t env, const int32_t serverType, const std::string& ip, const int32_t port);
  void send_delProvider(const std::string& appkey, const int32_t env, const int32_t serverType, const std::string& ip, const int32_t port);
  bool recv_delProvider();
  void getAppkeyListByIP(AppKeyListResponse& _return, const std::string& ip);
  void send_getAppkeyListByIP(const std::string& ip);
  void recv_getAppkeyListByIP(AppKeyListResponse& _return);
  void registerService(RegisterResponse& _return, const SGService& registerInfo);
  void send_registerService(const SGService& registerInfo);
  void recv_registerService(RegisterResponse& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class MNSCacheServiceProcessor : public ::apache::thrift::TProcessor {
 protected:
  boost::shared_ptr<MNSCacheServiceIf> iface_;
  virtual bool process_fn(apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot, std::string& fname, int32_t seqid, void* callContext);
 private:
  std::map<std::string, void (MNSCacheServiceProcessor::*)(int32_t, apache::thrift::protocol::TProtocol*, apache::thrift::protocol::TProtocol*, void*)> processMap_;
  void process_getMNSCache(int32_t seqid, apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_getMNSCache4HLB(int32_t seqid, apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_getMNSCacheWithVersionCheck(int32_t seqid, apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_getMNSCacheByAppkeys(int32_t seqid, apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_getAppKeyListByBusinessLine(int32_t seqid, apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_getHttpPropertiesByBusinessLine(int32_t seqid, apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_getHttpPropertiesByAppkey(int32_t seqid, apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_getGroupsByAppkey(int32_t seqid, apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_getAllGroups(int32_t seqid, apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_getSandbox(int32_t seqid, apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_saveSandbox(int32_t seqid, apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_deleteSandbox(int32_t seqid, apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_getSandboxConfig(int32_t seqid, apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_getProvidersByIP(int32_t seqid, apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_delProvider(int32_t seqid, apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_getAppkeyListByIP(int32_t seqid, apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_registerService(int32_t seqid, apache::thrift::protocol::TProtocol* iprot, apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  MNSCacheServiceProcessor(boost::shared_ptr<MNSCacheServiceIf> iface) :
    iface_(iface) {
    processMap_["getMNSCache"] = &MNSCacheServiceProcessor::process_getMNSCache;
    processMap_["getMNSCache4HLB"] = &MNSCacheServiceProcessor::process_getMNSCache4HLB;
    processMap_["getMNSCacheWithVersionCheck"] = &MNSCacheServiceProcessor::process_getMNSCacheWithVersionCheck;
    processMap_["getMNSCacheByAppkeys"] = &MNSCacheServiceProcessor::process_getMNSCacheByAppkeys;
    processMap_["getAppKeyListByBusinessLine"] = &MNSCacheServiceProcessor::process_getAppKeyListByBusinessLine;
    processMap_["getHttpPropertiesByBusinessLine"] = &MNSCacheServiceProcessor::process_getHttpPropertiesByBusinessLine;
    processMap_["getHttpPropertiesByAppkey"] = &MNSCacheServiceProcessor::process_getHttpPropertiesByAppkey;
    processMap_["getGroupsByAppkey"] = &MNSCacheServiceProcessor::process_getGroupsByAppkey;
    processMap_["getAllGroups"] = &MNSCacheServiceProcessor::process_getAllGroups;
    processMap_["getSandbox"] = &MNSCacheServiceProcessor::process_getSandbox;
    processMap_["saveSandbox"] = &MNSCacheServiceProcessor::process_saveSandbox;
    processMap_["deleteSandbox"] = &MNSCacheServiceProcessor::process_deleteSandbox;
    processMap_["getSandboxConfig"] = &MNSCacheServiceProcessor::process_getSandboxConfig;
    processMap_["getProvidersByIP"] = &MNSCacheServiceProcessor::process_getProvidersByIP;
    processMap_["delProvider"] = &MNSCacheServiceProcessor::process_delProvider;
    processMap_["getAppkeyListByIP"] = &MNSCacheServiceProcessor::process_getAppkeyListByIP;
    processMap_["registerService"] = &MNSCacheServiceProcessor::process_registerService;
  }

  virtual bool process(boost::shared_ptr<apache::thrift::protocol::TProtocol> piprot, boost::shared_ptr<apache::thrift::protocol::TProtocol> poprot, void* callContext);
  virtual ~MNSCacheServiceProcessor() {}
};

class MNSCacheServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  MNSCacheServiceProcessorFactory(const ::boost::shared_ptr< MNSCacheServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< MNSCacheServiceIfFactory > handlerFactory_;
};

class MNSCacheServiceMultiface : virtual public MNSCacheServiceIf {
 public:
  MNSCacheServiceMultiface(std::vector<boost::shared_ptr<MNSCacheServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~MNSCacheServiceMultiface() {}
 protected:
  std::vector<boost::shared_ptr<MNSCacheServiceIf> > ifaces_;
  MNSCacheServiceMultiface() {}
  void add(boost::shared_ptr<MNSCacheServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void getMNSCache(MNSResponse& _return, const std::string& appkey, const std::string& version, const std::string& env) {
    size_t sz = ifaces_.size();
    for (size_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->getMNSCache(_return, appkey, version, env);
        return;
      } else {
        ifaces_[i]->getMNSCache(_return, appkey, version, env);
      }
    }
  }

  void getMNSCache4HLB(MNSResponse& _return, const std::string& appkey, const std::string& version, const std::string& env) {
    size_t sz = ifaces_.size();
    for (size_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->getMNSCache4HLB(_return, appkey, version, env);
        return;
      } else {
        ifaces_[i]->getMNSCache4HLB(_return, appkey, version, env);
      }
    }
  }

  void getMNSCacheWithVersionCheck(MNSResponse& _return, const MnsRequest& req) {
    size_t sz = ifaces_.size();
    for (size_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->getMNSCacheWithVersionCheck(_return, req);
        return;
      } else {
        ifaces_[i]->getMNSCacheWithVersionCheck(_return, req);
      }
    }
  }

  void getMNSCacheByAppkeys(MNSBatchResponse& _return, const std::vector<std::string> & appkeys, const std::string& protocol) {
    size_t sz = ifaces_.size();
    for (size_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->getMNSCacheByAppkeys(_return, appkeys, protocol);
        return;
      } else {
        ifaces_[i]->getMNSCacheByAppkeys(_return, appkeys, protocol);
      }
    }
  }

  void getAppKeyListByBusinessLine(AppKeyListResponse& _return, const int32_t bizCode, const std::string& env) {
    size_t sz = ifaces_.size();
    for (size_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->getAppKeyListByBusinessLine(_return, bizCode, env);
        return;
      } else {
        ifaces_[i]->getAppKeyListByBusinessLine(_return, bizCode, env);
      }
    }
  }

  void getHttpPropertiesByBusinessLine(HttpPropertiesResponse& _return, const int32_t bizCode, const std::string& env) {
    size_t sz = ifaces_.size();
    for (size_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->getHttpPropertiesByBusinessLine(_return, bizCode, env);
        return;
      } else {
        ifaces_[i]->getHttpPropertiesByBusinessLine(_return, bizCode, env);
      }
    }
  }

  void getHttpPropertiesByAppkey(HttpPropertiesResponse& _return, const std::string& appkey, const std::string& env) {
    size_t sz = ifaces_.size();
    for (size_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->getHttpPropertiesByAppkey(_return, appkey, env);
        return;
      } else {
        ifaces_[i]->getHttpPropertiesByAppkey(_return, appkey, env);
      }
    }
  }

  void getGroupsByAppkey(HttpGroupResponse& _return, const std::string& appkey, const std::string& env) {
    size_t sz = ifaces_.size();
    for (size_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->getGroupsByAppkey(_return, appkey, env);
        return;
      } else {
        ifaces_[i]->getGroupsByAppkey(_return, appkey, env);
      }
    }
  }

  void getAllGroups(AllHttpGroupsResponse& _return, const std::string& env) {
    size_t sz = ifaces_.size();
    for (size_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->getAllGroups(_return, env);
        return;
      } else {
        ifaces_[i]->getAllGroups(_return, env);
      }
    }
  }

  void getSandbox(SandboxResponse& _return, const std::string& appkey, const std::string& env) {
    size_t sz = ifaces_.size();
    for (size_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->getSandbox(_return, appkey, env);
        return;
      } else {
        ifaces_[i]->getSandbox(_return, appkey, env);
      }
    }
  }

  bool saveSandbox(const std::string& id, const std::string& env, const std::string& data) {
    size_t sz = ifaces_.size();
    for (size_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        return ifaces_[i]->saveSandbox(id, env, data);
      } else {
        ifaces_[i]->saveSandbox(id, env, data);
      }
    }
  }

  bool deleteSandbox(const std::string& id, const std::string& env) {
    size_t sz = ifaces_.size();
    for (size_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        return ifaces_[i]->deleteSandbox(id, env);
      } else {
        ifaces_[i]->deleteSandbox(id, env);
      }
    }
  }

  void getSandboxConfig(std::vector<SandboxConfig> & _return, const std::vector<std::string> & appkeys, const std::string& env) {
    size_t sz = ifaces_.size();
    for (size_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->getSandboxConfig(_return, appkeys, env);
        return;
      } else {
        ifaces_[i]->getSandboxConfig(_return, appkeys, env);
      }
    }
  }

  void getProvidersByIP(MNSResponse& _return, const std::string& ip) {
    size_t sz = ifaces_.size();
    for (size_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->getProvidersByIP(_return, ip);
        return;
      } else {
        ifaces_[i]->getProvidersByIP(_return, ip);
      }
    }
  }

  bool delProvider(const std::string& appkey, const int32_t env, const int32_t serverType, const std::string& ip, const int32_t port) {
    size_t sz = ifaces_.size();
    for (size_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        return ifaces_[i]->delProvider(appkey, env, serverType, ip, port);
      } else {
        ifaces_[i]->delProvider(appkey, env, serverType, ip, port);
      }
    }
  }

  void getAppkeyListByIP(AppKeyListResponse& _return, const std::string& ip) {
    size_t sz = ifaces_.size();
    for (size_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->getAppkeyListByIP(_return, ip);
        return;
      } else {
        ifaces_[i]->getAppkeyListByIP(_return, ip);
      }
    }
  }

  void registerService(RegisterResponse& _return, const SGService& registerInfo) {
    size_t sz = ifaces_.size();
    for (size_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->registerService(_return, registerInfo);
        return;
      } else {
        ifaces_[i]->registerService(_return, registerInfo);
      }
    }
  }

};



#endif
