/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef operation_common_CONSTANTS_H
#define operation_common_CONSTANTS_H

#include "operation_common_types.h"

namespace com { namespace sankuai { namespace cmtrace {

class operation_commonConstants {
 public:
  operation_commonConstants();

};

extern const operation_commonConstants g_operation_common_constants;

}}} // namespace

#endif
