/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef sgagent_service_CONSTANTS_H
#define sgagent_service_CONSTANTS_H

#include "sgagent_service_types.h"



class sgagent_serviceConstants {
 public:
  sgagent_serviceConstants();

};

extern const sgagent_serviceConstants g_sgagent_service_constants;



#endif
