/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef quota_common_CONSTANTS_H
#define quota_common_CONSTANTS_H

#include "quota_common_types.h"



class quota_commonConstants {
 public:
  quota_commonConstants();

  std::string DEFAULT_CONSUMER_APPKEY;
};

extern const quota_commonConstants g_quota_common_constants;



#endif
