/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "sg_worker_service_constants.h"



const sg_worker_serviceConstants g_sg_worker_service_constants;

sg_worker_serviceConstants::sg_worker_serviceConstants() {
}



