/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "controller_constants.h"

namespace Controller {

const controllerConstants g_controller_constants;

controllerConstants::controllerConstants() {
}

} // namespace

